extends Node

@warning_ignore_start("unused_signal")
signal show_add_question_screen
signal hide_add_question_screen
signal current_question_deleted
signal all_questions_deleted
signal new_question_added
signal questions_imported
signal shuffle_deck
signal main_menu_play_pressed
signal main_menu_settings_pressed
signal main_menu_filter_pressed
signal main_menu_help_pressed
signal card_screen_exit_pressed
signal help_screen_exit_pressed
signal settings_screen_exit_pressed
signal filters_screen_exit_pressed
signal card_swipe_left
signal card_swipe_right
signal android_back_request
signal reset_deck_default
signal font_size_less
signal font_size_more
